### PR TITLE
ZBUG-2666:No information for CSR review operation from ZimbraWebAdmin

### PR DESCRIPTION
**Pull request by gabhinavTI**
https://jira.corp.synacor.com/browse/ZBUG-2666

Problem:
No information for CSR review operation from ZimbraWebAdmin

Code fix:
The issue was in  `parseSubject()` in `OutputParser.java` . Basically, the key_pattern and value_pattern weren't formed properly which resulted in the value not displaying once it was fixed the values started displaying
Test:
Manual test Through the Admin UI portal by observing the value in the fields.

### CODE REVIEW

**Review by k-kato — COMMENTED** [review]
Question:
Don't we need to keep backward compatibility? What happens if a CSR has already been created using an old version of zimbra-openssl module?

**Comment by yyoshiho** [comment]
About the backward compatibility, I agree to care of old format because customer may still use old CSR file.
If it is difficult for some reasons, we need to note the change of format in the release notes and customer needs to re-generate the CSR for new certificate.

**Comment by gabhinavTI** [comment]
> Question: Don't we need to keep backward compatibility? What happens if a CSR has already been created using an old version of zimbra-openssl module?

@k-kato, As suggested to Generate CSR  on version 9 Patch 10 and confirm the details are available on Version 9patch 24. The code takes care of backward compatibility as well

Attaching verification and screenshot below:
`Release 9.0.0.GA.3924.UBUNTU18.64 UBUNTU18_64 NETWORK edition, Patch 9.0.0_P24.1.`

Verification:
- install P10 and create CSR. The info is shown on Admin Console. 
- upgrade to P24. The CSR info is not shown on Admin Console  
- deploy new jar with PR code. The old CSR info should is shown on Admin Console 
- recreate a new CSR with the new format. The CSR info is shown on Admin Console. 

Screenshot of CSR details which was created on P10 and viewed on P24:

Screenshot 2022-05-24 at 12 44 54 PM
Screenshot 2022-05-24 at 12 44 44 PM

cc- @yyoshiho

**Review by k-kato — APPROVED** [review]
@gabhinavTI thank you very much for your confirmation.
I checked the code as well. Even when a CSR has been created on ZCS 9.0.0 P10 or using openssl 1.0.2, the csr is decoded in a new format calling `zmcertmgr viewcsr` command on P24.1, which uses openssl 1.1.1. Then the regex works as expected.

nit: please fix the example at line 85 to new format.
For example,
`subject=C = US, ST = NY, L = Buffalo, O = "Synacor, Inc.", OU = Zimbra Collaboration Suite, CN = admindev.zimbra.com`

**Comment by gabhinavTI** [comment]
> @gabhinavTI thank you very much for your confirmation. I checked the code as well. Even when a CSR has been created on ZCS 9.0.0 P10 or using openssl 1.0.2, the csr is decoded in a new format calling `zmcertmgr viewcsr` command on P24.1, which uses openssl 1.1.1. Then the regex works as expected.
> 
> nit: please fix the example at line 85 to new format. For example, `subject=C = US, ST = NY, L = Buffalo, O = "Synacor, Inc.", OU = Zimbra Collaboration Suite, CN = admindev.zimbra.com`

Done

**Review by shrutig0510 — APPROVED** [review]

**Review by dasiyogesh — APPROVED** [review]

**Pull request merged**
