### PR TITLE
ZBUG:1397: Admin GUI doesn't allow to create a CSR if OU or O contains single quote (')

### PR DESCRIPTION
**Pull request by gabhinavTI**

### CODE REVIEW

**Comment by gabhinavTI** [comment]
https://jira.corp.synacor.com/browse/ZBUG-1397

Problem:
Admin GUI doesn't allow the creation of a CSR if OU or O contains a single quote ('). If the single quote is passed in the OU or O field then it throws the error

Code fix:
The issue was when the command formed in the `GenerateCSR.java` class in code `subject` and `subjectAltNames` was quoted using single quotes, and when single quotes passed in OU or O the single quote wouldn't end properly and hence command would fail. To fix this replaced the single quotes with double quotes which fixed the command 


Test:
Through the Admin UI portal by passing single quote(') in OU or O

**Comment by silentsakky** [comment]
Commits are not having ticket number as first word, please update that

**Review by shrutig0510 — APPROVED** [review]

**Comment by silentsakky** [comment]
Does this fix allows double quotes now?

**Comment by gabhinavTI** [comment]
> Does this fix allows double quotes now?

@silentsakky double quotes is not allowed in those field, there is validation for not allowing same

**Comment by gabhinavTI** [comment]
> Commits are not having ticket number as first word, please update that

renamed to have ticket number in commit first

**Review by silentsakky — APPROVED** [review]

**Review by preshitaagrawal — APPROVED** [review]

**Review by dasiyogesh — APPROVED** [review]

**Review by ronstra-synacor — APPROVED** [review]
This should probably use some well-known shell-escaping library to build the command string, but so long as there are restrictions against double-quotes in these quoted values, should be OK.

**Pull request merged**
